# Generated by Django 2.0.9 on 2019-02-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='member_list',
            new_name='members_limit',
        ),
    ]
